defmodule AvaliaUsp.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:professores) do
      remove :nome
      add :primeiro_nome, :text
      add :sobrenome, :text
      add :email, :text
    end
  end

  def down do
    alter table(:professores) do
      remove :email
      remove :sobrenome
      remove :primeiro_nome
      add :nome, :text
    end
  end
end
