defmodule AvaliaUsp.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:avaliacaos, [:avaliador_id, :disciplina_id, :professor_id],
             name: "avaliacaos_unique_avalicao_por_avaliador_index"
           )
  end

  def down do
    drop_if_exists unique_index(:avaliacaos, [:avaliador_id, :disciplina_id, :professor_id],
                     name: "avaliacaos_unique_avalicao_por_avaliador_index"
                   )
  end
end
