defmodule AvaliaUsp.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:disciplinas) do
      add :codigo, :text, null: false
    end

    create unique_index(:disciplinas, [:codigo, :nome],
             name: "disciplinas_unique_nome_completo_index"
           )
  end

  def down do
    drop_if_exists unique_index(:disciplinas, [:codigo, :nome],
                     name: "disciplinas_unique_nome_completo_index"
                   )

    alter table(:disciplinas) do
      remove :codigo
    end
  end
end
