defmodule AvaliaUsp.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:professores) do
      add :profile_picture_url, :text, default: "/images/default_profile_pic.png"
    end
  end

  def down do
    alter table(:professores) do
      remove :profile_picture_url
    end
  end
end
