defmodule AvaliaUsp.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:avaliacaos) do
      add :disciplina_id,
          references(:disciplinas,
            column: :id,
            name: "avaliacaos_disciplina_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:avaliacaos, "avaliacaos_disciplina_id_fkey")

    alter table(:avaliacaos) do
      remove :disciplina_id
    end
  end
end
