defmodule AvaliaUsp.Repo.Migrations.MigrateResources19 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:avaliacaos) do
      modify :encrypted_comentario, :binary, null: false
    end
  end

  def down do
    alter table(:avaliacaos) do
      modify :encrypted_comentario, :binary, null: true
    end
  end
end
