defmodule AvaliaUsp.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:avaliacaos) do
      add :avaliador_id,
          references(:users,
            column: :id,
            name: "avaliacaos_avaliador_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:avaliacaos, "avaliacaos_avaliador_id_fkey")

    alter table(:avaliacaos) do
      remove :avaliador_id
    end
  end
end
