defmodule AvaliaUsp.Repo.Migrations.MigrateResources18 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:avaliacaos) do
      add :comentario_avaliacao, :text
      add :comentario_presenca, :text
    end
  end

  def down do
    alter table(:avaliacaos) do
      remove :comentario_presenca
      remove :comentario_avaliacao
    end
  end
end
