defmodule AvaliaUsp.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:solicitacao_disciplinas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :nome_disciplina, :text, null: false
      add :comentario, :text
      add :links_uteis, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "solicitacao_disciplinas_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :professor_id,
          references(:professores,
            column: :id,
            name: "solicitacao_disciplinas_professor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:solicitacao_disciplinas, "solicitacao_disciplinas_user_id_fkey")

    drop constraint(:solicitacao_disciplinas, "solicitacao_disciplinas_professor_id_fkey")

    drop table(:solicitacao_disciplinas)
  end
end
