defmodule AvaliaUsp.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:disciplinas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :nome, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:disciplina_professors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :disciplina_id,
          references(:disciplinas,
            column: :id,
            name: "disciplina_professors_disciplina_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :professor_id,
          references(:professores,
            column: :id,
            name: "disciplina_professors_professor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:disciplina_professors, "disciplina_professors_disciplina_id_fkey")

    drop constraint(:disciplina_professors, "disciplina_professors_professor_id_fkey")

    drop table(:disciplina_professors)

    drop table(:disciplinas)
  end
end
