defmodule AvaliaUsp.Repo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:avaliacaos) do
      add :cobra_presenca, :boolean, null: false
    end
  end

  def down do
    alter table(:avaliacaos) do
      remove :cobra_presenca
    end
  end
end
