defmodule AvaliaUsp.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:professores, [:email], name: "professores_unique_email_index")

    create unique_index(:professores, [:primeiro_nome, :sobrenome],
             name: "professores_unique_nome_completo_index"
           )
  end

  def down do
    drop_if_exists unique_index(:professores, [:primeiro_nome, :sobrenome],
                     name: "professores_unique_nome_completo_index"
                   )

    drop_if_exists unique_index(:professores, [:email], name: "professores_unique_email_index")
  end
end
